name: Security & Dependency Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  audit:
    name: Security & Dependency Audit  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install cargo-deny
      run: cargo install --locked cargo-deny
    
    - name: Run comprehensive dependency audit
      run: cargo deny check
      
    - name: Run security vulnerability check only
      run: cargo deny check advisories